apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.cronjob.name | default .Release.Name }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
spec:
  schedule: "{{ .Values.cronjob.schedule }}"
  successfulJobsHistoryLimit: {{ .Values.cronjob.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.cronjob.failedJobsHistoryLimit }}
  jobTemplate:
    metadata:
      labels:
        {{- range $k, $v := .Values.cronjob.labels }}
        {{ $k }}: {{ $v }}
        {{- end }}
    spec:
      backoffLimit: {{ .Values.cronjob.backoffLimit }}
      template:
        spec:
          serviceAccountName: {{ .Values.serviceaccount.name }}
          restartPolicy: {{ .Values.cronjob.restartPolicy }}
          containers:
          - name: {{ .Values.cronjob.name | default .Release.Name }}
            image: {{ .Values.cronjob.image }}
            imagePullPolicy: {{ .Values.cronjob.imagePullPolicy }}
            command: [ {{ .Values.cronjob.command }} ]
            args:
            {{ .Values.cronjob.args | toYaml }}
            resources:
              requests:
                cpu: {{ .Values.cronjob.requests.cpu }}
                memory: {{ .Values.cronjob.requests.memory }}
